# Generated by Django 3.2.9 on 2021-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapi", "0002_auto_20211128_1511"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="creator",
        ),
        migrations.AddField(
            model_name="news",
            name="author_name",
            field=models.CharField(default="Anonimus=)", max_length=50),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(max_length=50),
        ),
    ]
