# Generated by Django 3.2.9 on 2021-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapi", "0003_auto_20211128_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(default="SOME STRING", max_length=50),
        ),
        migrations.AlterField(
            model_name="news",
            name="author_name",
            field=models.CharField(default="SOME STRING", max_length=50),
        ),
    ]
