# Generated by Django 3.2.9 on 2021-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapi", "0004_auto_20211128_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
